# Generated by Django 3.0.3 on 2020-04-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='count',
        ),
        migrations.AddField(
            model_name='entry',
            name='active_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='new_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='new_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
    ]
