# Generated by Django 3.0.3 on 2020-04-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='active_cases',
            new_name='deaths',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='new_cases',
            new_name='recovered',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='new_deaths',
            new_name='serial',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='total_deaths',
        ),
    ]
