# Generated by Django 3.0.5 on 2020-04-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20200408_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
