# Generated by Django 3.0.5 on 2020-04-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20200410_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='serial',
            new_name='active',
        ),
    ]
