# Generated by Django 3.0.5 on 2020-04-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0007_auto_20200412_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wap_number', models.CharField(max_length=15)),
            ],
        ),
    ]
